# Generated by Django 3.2.8 on 2021-10-21 09:02

import uuid

import bettersocial.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name = 'Author',
            fields = [
                ('id', models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('uuid', models.UUIDField(default = uuid.uuid4, editable = False, unique = True)),
                ('github_url', models.CharField(max_length = 255, null = True)),
                ('user', models.OneToOneField(on_delete = django.db.models.deletion.CASCADE, to = settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name = 'Node',
            fields = [
                ('id', models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('host', models.CharField(max_length = 255, unique = True)),
                ('prefix', models.CharField(default = 'service', max_length = 32)),
                ('auth_username', models.CharField(max_length = 255)),
                ('auth_password', models.CharField(max_length = 255)),
                ('node_username', models.CharField(max_length = 255)),
                ('node_password', models.CharField(max_length = 255)),
            ],
        ),
        migrations.CreateModel(
            name = 'Post',
            fields = [
                ('id', models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('uuid', models.UUIDField(default = uuid.uuid4, editable = False, unique = True)),
                ('content_type', models.CharField(choices = [('text/plain', 'Text'), ('text/markdown', 'Markdown'), ('application/base64', 'Base64 Encoded'), ('image/png', 'Image (PNG)'), ('image/jpeg', 'Image (JPEG)')], default = 'text/plain', max_length = 32)),
                ('title', models.CharField(max_length = 255)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('categories', models.JSONField(default = list, validators = [bettersocial.validators.validate_categories])),
                ('visibility', models.CharField(choices = [('PUBLIC', 'Public'), ('FRIENDS', 'Friends')], default = 'PUBLIC', max_length = 32)),
                ('unlisted', models.BooleanField(default = False)),
                ('published', models.DateTimeField(auto_now_add = True)),
                ('author', models.ForeignKey(on_delete = django.db.models.deletion.CASCADE, to = 'bettersocial.author')),
            ],
            options = {
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name = 'Inbox',
            fields = [
                ('id', models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('object', models.JSONField(default = dict)),
                ('author', models.ForeignKey(on_delete = django.db.models.deletion.CASCADE, to = 'bettersocial.author')),
            ],
        ),
        migrations.CreateModel(
            name = 'Comment',
            fields = [
                ('id', models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('uuid', models.UUIDField(default = uuid.uuid4, editable = False, unique = True)),
                ('author', models.UUIDField()),
                ('content_type', models.CharField(choices = [('text/plain', 'Text'), ('text/markdown', 'Markdown'), ('application/base64', 'Base64 Encoded'), ('image/png', 'Image (PNG)'), ('image/jpeg', 'Image (JPEG)')], default = 'text/plain', max_length = 32)),
                ('comment', models.TextField()),
                ('published', models.DateTimeField(auto_now_add = True)),
                ('post', models.ForeignKey(on_delete = django.db.models.deletion.CASCADE, to = 'bettersocial.post')),
            ],
            options = {
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name = 'UUIDRemoteCache',
            fields = [
                ('uuid', models.UUIDField(primary_key = True, serialize = False)),
                ('dj_content_type', models.ForeignKey(limit_choices_to = models.Q(('model', 'author'), ('model', 'post'), ('model', 'comment'), _connector = 'OR'), on_delete = django.db.models.deletion.CASCADE, to = 'contenttypes.contenttype')),
                ('node', models.ForeignKey(on_delete = django.db.models.deletion.CASCADE, to = 'bettersocial.node')),
            ],
            options = {
                'unique_together': { ('uuid', 'dj_content_type') },
            },
        ),
        migrations.CreateModel(
            name = 'LikedRemote',
            fields = [
                ('id', models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('uuid_object', models.UUIDField()),
                ('author', models.ForeignKey(on_delete = django.db.models.deletion.CASCADE, to = 'bettersocial.author')),
                ('dj_content_type', models.ForeignKey(limit_choices_to = models.Q(('model', 'post'), ('model', 'comment'), _connector = 'OR'), on_delete = django.db.models.deletion.CASCADE, to = 'contenttypes.contenttype')),
            ],
            options = {
                'unique_together': { ('author', 'uuid_object') },
            },
        ),
        migrations.CreateModel(
            name = 'Like',
            fields = [
                ('id', models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('author', models.UUIDField()),
                ('dj_object_id', models.PositiveIntegerField()),
                ('dj_content_type', models.ForeignKey(limit_choices_to = models.Q(('model', 'post'), ('model', 'comment'), _connector = 'OR'), on_delete = django.db.models.deletion.CASCADE, to = 'contenttypes.contenttype')),
            ],
            options = {
                'unique_together': { ('author', 'dj_object_id', 'dj_content_type') },
            },
        ),
        migrations.CreateModel(
            name = 'Following',
            fields = [
                ('id', models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('following', models.UUIDField()),
                ('author', models.ForeignKey(on_delete = django.db.models.deletion.CASCADE, to = 'bettersocial.author')),
            ],
            options = {
                'unique_together': { ('author', 'following') },
            },
        ),
        migrations.CreateModel(
            name = 'Follower',
            fields = [
                ('id', models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('follower', models.UUIDField()),
                ('author', models.ForeignKey(on_delete = django.db.models.deletion.CASCADE, to = 'bettersocial.author')),
            ],
            options = {
                'unique_together': { ('author', 'follower') },
            },
        ),
    ]
