# Generated by Django 3.2.8 on 2021-10-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bettersocial', '0002_uuid_foreign_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='object',
            new_name='inbox_object',
        ),
    ]
