# Generated by Django 3.2.8 on 2021-10-27 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bettersocial', '0003_remove_post_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
