# Generated by Django 3.2.8 on 2021-11-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bettersocial', '0004_auto_20211029_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name = 'node',
            name = 'adapter_id',
            field = models.CharField(choices = [('default', 'default'), ('team_1', 'team_1')], default = 'default', max_length = 32),
        ),
        migrations.AlterField(
            model_name = 'node',
            name = 'prefix',
            field = models.CharField(blank = True, default = 'service', max_length = 32),
        ),
    ]
