# Generated by Django 3.1.6 on 2021-11-23 21:35

import bettersocial.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettersocial', '0004_auto_20211029_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_username',
        ),
        migrations.AlterField(
            model_name='follower',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='following',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='likedremote',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.JSONField(blank=True, default=list, validators=[bettersocial.validators.validate_categories]),
        ),
        migrations.AlterField(
            model_name='post',
            name='recipient_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
