# Generated by Django 3.2.8 on 2021-10-27 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bettersocial', '0004_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
    ]
