# Generated by Django 3.2.8 on 2021-11-25 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bettersocial', '0005_add_adapter_and_fix_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name = 'InboxItem',
            fields = [
                ('id', models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('inbox_object', models.JSONField(default = dict)),
                ('author', models.ForeignKey(on_delete = django.db.models.deletion.CASCADE, to = 'bettersocial.author')),
                ('dj_content_type', models.ForeignKey(limit_choices_to = models.Q(('model', 'post'), ('model', 'comment'), ('model', 'like'), ('model', 'follower'), _connector = 'OR'), on_delete = django.db.models.deletion.CASCADE, to = 'contenttypes.contenttype')),
            ],
            options = {
                'verbose_name': 'InboxItem',
                'verbose_name_plural': 'InboxItem',
            },
        ),
        migrations.DeleteModel(
            name = 'Inbox',
        ),
    ]
