# Generated by Django 3.2.8 on 2021-11-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bettersocial', '0006_rename_inbox_inboxitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name = 'node',
            name = 'adapter_id',
            field = models.CharField(choices = [('default', 'default'), ('team_1', 'team_1'), ('team_4', 'team_4')], default = None, max_length = 32),
        ),
    ]
