# Generated by Django 3.2.8 on 2021-11-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bettersocial', '0007_alter_node_adapter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name = 'node',
            name = 'adapter_id',
            field = models.CharField(choices = [('default', 'default'), ('team_1', 'team_1'), ('team_4', 'team_4')], default = 'default', max_length = 32),
        ),
        migrations.AlterUniqueTogether(
            name = 'uuidremotecache',
            unique_together = { ('uuid', 'node') },
        ),
        migrations.RemoveField(
            model_name = 'uuidremotecache',
            name = 'dj_content_type',
        ),
    ]
