# Generated by Django 3.1.6 on 2021-10-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettersocial', '0008_auto_20211027_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_username',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
