# Generated by Django 3.2.8 on 2021-11-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bettersocial', '0009_auto_20211126_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name = 'post',
            name = 'image_content',
        ),
        migrations.AlterField(
            model_name = 'follower',
            name = 'id',
            field = models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID'),
        ),
        migrations.AlterField(
            model_name = 'following',
            name = 'id',
            field = models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID'),
        ),
        migrations.AlterField(
            model_name = 'inboxitem',
            name = 'id',
            field = models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID'),
        ),
        migrations.AlterField(
            model_name = 'like',
            name = 'id',
            field = models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID'),
        ),
        migrations.AlterField(
            model_name = 'likedremote',
            name = 'id',
            field = models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID'),
        ),
        migrations.AlterField(
            model_name = 'node',
            name = 'id',
            field = models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID'),
        ),
    ]
