# Generated by Django 3.2.8 on 2021-10-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettersocial', '0011_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
