# Generated by Django 3.2.8 on 2021-10-28 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bettersocial', '0003_rename_object_inbox_inbox_object'),
        ('bettersocial', '0012_alter_post_content'),
    ]

    operations = [
    ]
