# Generated by Django 3.2.8 on 2021-12-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bettersocial', '0012_node_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name = 'node',
            name = 'adapter_id',
            field = models.CharField(choices = [('default', 'default'), ('team_1', 'team_1'), ('team_4', 'team_4'), ('team_7', 'team_7')], default = 'default', max_length = 32),
        ),
        migrations.AlterField(
            model_name = 'node',
            name = 'display_name',
            field = models.CharField(blank = True, max_length = 127),
        ),
    ]
