# Generated by Django 3.2.8 on 2021-10-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettersocial', '0013_merge_20211028_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='inbox_object',
        ),
        migrations.AddField(
            model_name='inbox',
            name='object',
            field=models.JSONField(default=dict),
        ),
    ]
