# Generated by Django 3.2.8 on 2021-10-28 23:32

import bettersocial.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettersocial', '0014_auto_20211028_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='object',
            new_name='inbox_object',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.JSONField(default=list, validators=[bettersocial.validators.validate_categories]),
        ),
    ]
